### PR TITLE
Dev peter with heatmap label resize

### PR DESCRIPTION
**Pull request by psolymos**

### CODE REVIEW

**Review by dwightkuo — COMMENTED** [review]
Looks like most of these changes are to the ui and server calls. Can you integrate these directly into the Secondary_Analysis_Module repo?

**Comment by psolymos** [comment]
The shiny server is the function being called by SAM, and the changes should be available once the package is updated inside the container (i.e. after the merge and the next build). We can make a beta2 branch or pin the commit SHA to make versioning more explicit in the Dockerfile. If you mean the changes in the `inst/_tmp/index.R` file -- this is only for testing purposes.

**Comment by dwightkuo** [comment]
Screenshot 2023-08-31 at 18 58 40
This is what I see when I try it within the app

**Comment by psolymos** [comment]
@dwightkuo the font size has a minimum of 5pt, which is the same as the lowest end of the label slider. What the smallest font size should be? Setting the minimum to 1 seem to work better. The size also resets when one uses the slider.

**Comment by dwightkuo** [comment]
Is this based on screen size as opposed to window size? When I move the same window from my laptop screen to an external monitor the text disappears
Screenshot 2023-08-31 at 21 07 00
Screenshot 2023-08-31 at 21 07 07

Also the text still isn't right on the laptop screen

**Comment by psolymos** [comment]
Can you copy the messages from the R session when you move to an external screen? It prints out the width/height and the % change when resizing.

**Comment by dwightkuo** [comment]
Listening on http://127.0.0.1:6213
2023-09-01 07:35:30.389754 INFO All ANA expected secrets/credentials found as environment variables!
Original heatmap: H=500px, W=690px
2023-09-01 07:35:32.824684 INFO All ANA expected secrets/credentials found as environment variables!
2023-09-01 07:35:32.825533 INFO All Blob Storage expected secrets/credentials found as environment variables!
Using client_credentials flow
Warning in renderWidget(instance) :
  Ignoring explicitly provided widget ID "main-projects-table"; Shiny doesn't use them
2023-09-01 07:35:36.680284 Updated updated_order_Plate_4
`summarise()` has grouped output by 'Covariate', 'plateID'. You can override using the `.groups` argument.
The `name` provided ('fa fa-pen-to-square') does not correspond to a known icon
2023-09-01 07:35:37.395745 INFO See below for a list of 207 selected targets!
2023-09-01 07:35:37.917796 INFO Project status updated!
Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(column_order)

  # Now:
  data %>% select(all_of(column_order))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
Warning in renderWidget(instance) :
  Ignoring explicitly provided widget ID "plates_summary_table"; Shiny doesn't use them
Warning in RColorBrewer::brewer.pal(unique_groups_length, name = set) :
  minimal value for n is 3, returning requested palette with 3 different levels

Warning in RColorBrewer::brewer.pal(unique_groups_length, name = set) :
  minimal value for n is 3, returning requested palette with 3 different levels

Warning in RColorBrewer::brewer.pal(unique_groups_length, name = set) :
  n too large, allowed maximum for palette Set1 is 9
Returning the palette you asked for with that many colors

Warning in RColorBrewer::brewer.pal(unique_groups_length, name = set) :
  minimal value for n is 3, returning requested palette with 3 different levels

Warning in RColorBrewer::brewer.pal(unique_groups_length, name = set) :
  minimal value for n is 3, returning requested palette with 3 different levels

**Pull request closed without merging**
