### PR TITLE
Fix Color bar labels by reproducing the main heatmap color range

### PR DESCRIPTION
**Pull request by psolymos**
Using `range` was not the best approximation to guess the color range shown in the main heatmap, which, depending on the actual data, can be symmetric around 0, that was ignored by `range`. The function also excludes extremes when the matrix is bug (>100 values). This is now captured in the implementation.

### CODE REVIEW

**Review by dwightkuo — COMMENTED** [review]
Screenshot 2023-11-23 at 23 24 40
I rebuilt InteractiveComplexHeatmap and tried it within NAS but this doesn't seem much better.

**Comment by psolymos** [comment]
Very strange

**Comment by dwightkuo** [comment]
> I am also working with Kasun et al. to get my RC1 local branch working. I am getting some data parsing error that they are looking int.
We just merged some PRs into RC1 of Secondary-Analysis-Module. This might have fixed your issue

**Comment by dwightkuo** [comment]
Screenshot 2023-11-27 at 15 57 23
One other thing if it's helpful is that it's not just that the zero is displayed in the wrong place, the actual color scale is set this way as well. Looking at the attached image, you can see that the cell that's highlighted has a bluish color and has a +ve value (e.g. 1.62).

**Comment by srsankhe** [comment]
@dwightkuo tried this branch locally on a subset of targets seems to work

Screenshot 2023-11-27 at 6 37 53 PM

**Comment by srsankhe** [comment]
> Screenshot 2023-11-27 at 15 57 23 One other thing if it's helpful is that it's not just that the zero is displayed in the wrong place, the actual color scale is set this way as well. Looking at the attached image, you can see that the cell that's highlighted has a bluish color and has a +ve value (e.g. 1.62).

Just noticed this as well, the 0 seems to be floating and kinda acts up in the subheatmap when these value are selected
Screenshot 2023-11-27 at 6 42 39 PM

**Comment by psolymos** [comment]
@dwightkuo new commit added that I think tackles this. Instead of trying to align the ranges, I used the color breaks and corresponding colors from ComplexHeatmap. I tested it in NAS and it looks good, 0 where it should be, color bar range corresponding to sub heatmap values.

**Review by dwightkuo — APPROVED** [review]
it works! awesome!

**Pull request merged**
